-- WowWed MySQL schema (single source of truth)
-- =============================================================
-- AUTO-SYNC: All statements here run automatically when the
-- backend starts (backend/config/initSchema.js) or when you run:
--   npm run db:init --prefix backend
--
-- To add a NEW table: append CREATE TABLE IF NOT EXISTS below.
-- No manual phpMyAdmin steps needed — restart the backend.
-- =============================================================

CREATE DATABASE IF NOT EXISTS wowwed CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE wowwed;
CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  full_name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  phone VARCHAR(20) DEFAULT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('couple', 'vendor') NOT NULL DEFAULT 'couple',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_login TIMESTAMP NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS onboarding (
  user_id INT PRIMARY KEY,
  data_json JSON NOT NULL,
  completed_at TIMESTAMP NULL DEFAULT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS wedding_profiles (
  user_id INT PRIMARY KEY,
  partner_one VARCHAR(100) DEFAULT NULL,
  partner_two VARCHAR(100) DEFAULT NULL,
  wedding_date DATE DEFAULT NULL,
  venue VARCHAR(255) DEFAULT NULL,
  district VARCHAR(50) DEFAULT NULL,
  ceremony_type VARCHAR(50) DEFAULT NULL,
  guest_count INT DEFAULT NULL,
  budget DECIMAL(15, 2) DEFAULT NULL,
  scale VARCHAR(50) DEFAULT NULL,
  venue_type VARCHAR(50) DEFAULT NULL,
  planning_stage VARCHAR(50) DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS vendor_profiles (
  user_id INT PRIMARY KEY,
  business_name VARCHAR(150) NOT NULL,
  category VARCHAR(100) DEFAULT NULL,
  district VARCHAR(50) DEFAULT NULL,
  price_range VARCHAR(50) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  portfolio_json JSON DEFAULT NULL,
  rating DECIMAL(2, 1) DEFAULT 4.5,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS vendor_listings (
  id VARCHAR(50) PRIMARY KEY,
  user_id INT DEFAULT NULL,
  name VARCHAR(150) NOT NULL,
  category VARCHAR(100) DEFAULT NULL,
  city VARCHAR(50) DEFAULT NULL,
  district VARCHAR(50) DEFAULT NULL,
  price_range VARCHAR(50) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  portfolio_json JSON DEFAULT NULL,
  rating DECIMAL(2, 1) DEFAULT 4.5,
  spotlight TINYINT(1) DEFAULT 0,
  owner_email VARCHAR(100) DEFAULT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS user_data (
  user_id INT NOT NULL,
  store_key VARCHAR(30) NOT NULL,
  data_json JSON NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, store_key),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
  id VARCHAR(50) PRIMARY KEY,
  couple_user_id INT NOT NULL,
  vendor_name VARCHAR(150) NOT NULL,
  vendor_email VARCHAR(100) DEFAULT NULL,
  couple_name VARCHAR(150) DEFAULT NULL,
  couple_email VARCHAR(100) DEFAULT NULL,
  booking_date DATE DEFAULT NULL,
  amount DECIMAL(15, 2) DEFAULT NULL,
  message TEXT DEFAULT NULL,
  status VARCHAR(20) DEFAULT 'Pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (couple_user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Seed vendor listings extracted from Desktop/Vendors (complete one-to-one 2026-2027 set)
-- To replace listings on an existing database, run docs/vendor_listings_seed.sql
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-01', 'Kandyan Reach Hotel', 'Venue & Res. Halls', 'Kurunegala', 'Kurunegala', '735000-1110000', 'Kurunegala wedding hotel with four all-inclusive packages from Rs. 4,900 to Rs. 7,400 per person (minimum 150 pax). Compliments include couple, registration and head tables, pool/lobby/pond photo locations, outdoor registration, changing room, decorated honeymoon room, dance floor and DJ/band stage.', '{"images": [], "quotations": [{"id": "kr-unity", "title": "Unity KRH Wedding Package", "price": "4900", "details": "Per person, min 150 pax. Menu: 1 welcome drink, 1 appetizer, 1 shooter, 5 salads, 4 dressings, 1 soup, steamed rice, 1 flavoured rice, noodles/pasta, chicken, fish, 4 veg, all condiments, 5 desserts. Compliments: tables, pool/lobby/pond photo locations, outdoor registration, changing room, honeymoon room, dance floor, DJ/band stage."}, {"id": "kr-essential", "title": "Essential Elegance Package", "price": "5300", "details": "Per person. Menu upgrades to 2 appetizers, 2 shooters, 7 salads, all dressings, 2 flavoured rice, 7 desserts. Adds wedding cards, unlimited bites and unlimited soft drinks."}, {"id": "kr-grand", "title": "Grand Celebration Package", "price": "6000", "details": "Same menu grid as Essential. Adds flower decorations, poruwa and settee back, Ashtaka, welcome dancers, Jayamangala Gatha, kiri kala, oil lamp and champagne fondant."}, {"id": "kr-bliss", "title": "Infinite Bliss Package", "price": "7400", "details": "Menu: 4 appetizers, 3 shooters, 9 salads, 2 soups, 3 flavoured rice, plus crabs or pork. Adds wedding car (25 km) and DJ with stage."}, {"id": "kr-addon", "title": "Add-on meats, bites and bar", "price": "300", "details": "Beef 400 pp, pork 300 pp, mutton 650 pp, action cooking per kg 3500-9000, dessert action 375, ice coffee at Mangala Sabawa 550. Bites per kg 2000-9000. Soft drinks 550-1400. Beer 1590-2350."}], "quotationPdf": null, "categories": ["Venue & Res. Halls", "Caters"], "districts": ["Kurunegala"]}', 4.7, 1, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-02', 'Hotel Queensbury', 'Venue & Res. Halls', 'Malabe', 'Colombo', '699000-699000', 'All-inclusive wedding package for 150 guests at Hotel Queensbury, Malabe. Includes traditional Ashtaka, welcome bites, flower decorations, kiri kala and poruwa tables, wedding-day coordination and live DJ.', '{"images": [], "quotations": [{"id": "qb-150", "title": "All Inclusive Wedding for 150 Guests", "price": "699000", "details": "Ashtaka ceremony, free welcome bites, flower decorations, kiri kala and poruwa tables, expert wedding-day coordination, live DJ. T&C apply."}], "quotationPdf": null, "categories": ["Venue & Res. Halls"], "districts": ["Colombo"]}', 4.6, 1, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-03', 'The Urban Fortress', 'Venue & Res. Halls', 'Colombo', 'Colombo', '18000-25000', 'Colombo heritage-style photo and event space with parking, catering options and styled backdrops. Hourly hire for pre-shoots, engagements and intimate celebrations.', '{"images": [], "quotations": [{"id": "uf-1h", "title": "1 Hour Venue Hire", "price": "18000", "details": "Additional time Rs. 5,000 per half hour. Parking, catering options and photo backdrops."}, {"id": "uf-2h", "title": "2 Hour Venue Hire", "price": "25000", "details": "Additional time Rs. 5,000 per half hour."}], "quotationPdf": null, "categories": ["Venue & Res. Halls"], "districts": ["Colombo"]}', 4.6, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-04', 'Grand Minaro Crystal Ballroom', 'Venue & Res. Halls', 'Panagoda', 'Colombo', '645000-2015000', 'All-inclusive Crystal Ballroom weddings in Panagoda. AC hall for 5 hours, LED lighting, bridal settee, outdoor poruwa location, LED dance floor, honeymoon room, salon and parking. Browns to Platinum menus from 100 to 250 pax.', '{"images": [], "quotations": [{"id": "gm-browns-150", "title": "Browns Package 150 pax", "price": "785000", "details": "Browns buffet. Hall compliments: AC banquet 5 hrs, LED lighting, settee, oil lamp, Tiffany chairs, free corkage, outdoor poruwa, salon, honeymoon room."}, {"id": "gm-silver-150", "title": "Silver Package 150 pax", "price": "980000", "details": "Silver menu LKR 5,600 nett pp. 12 kg bites + 10 L soft drinks. Decorations, DJ, Kandyan welcome, Jayamangala Gatha, Ashtaka, champagne/milk fountain. Compliments: roast/tandoori chicken appetizer, four shooters, basmati, hot butter mushroom, fish cutlet, ice coffee for 50% of plates."}, {"id": "gm-gold-150", "title": "Gold Package 150 pax", "price": "1137500", "details": "Gold menu Rs. 5,900 pp. Soup 1, salads 5, mains 4, 2 hot meats, seafood, 3 veg, 5 desserts."}, {"id": "gm-plat-150", "title": "Platinum Package 150 pax", "price": "1265000", "details": "Platinum menu Rs. 7,600 pp. Soup 1, salads 5, mains 5, 4 hot dishes, 3 veg, 5 desserts."}, {"id": "gm-bites", "title": "Bite menu for wedding functions (net/kg)", "price": "1450", "details": "Chicken 3900, pork/beef 5400, fish 4200, prawn 4500, cuttlefish 3950, veg items 1100-2850. Soft drinks 350-450, water 125-225."}], "quotationPdf": null, "categories": ["Venue & Res. Halls", "Caters"], "districts": ["Colombo"]}', 4.8, 1, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-05', 'The Barnhouse Sri Lanka', 'Venue & Res. Halls', 'Panadura', 'Kalutara', '950000-950000', 'Sherwood by the Barn at Kiriberiya, Panadura. All-inclusive 2026 engagement package with Studio U photography, decorations, DJ, dressing room and banquet menu. Venue capacity 60-120 pax. Valid 21 Sep 2025 to 31 Dec 2026.', '{"images": [], "quotations": [{"id": "bh-eng", "title": "All Inclusive Engagement Package 2026", "price": "950000", "details": "Studio U photography + videography (Kushantha or Dhanushka Hewapathirana), all digital photos, 10x20 30-page album, 12x18 framed enlargement, 30 edited images, Full HD 1-camera video on flash drive. Decorations: entrance, tables, ring backdrop, settee, oil lamp, head table. DJ. Complimentary dressing room, registration table, barn cake table. Extra pax Rs. 9,000. Min 80 pax. Hall 5 hours (morning 10am-3pm or evening 7pm-12am). Extra hour Rs. 45,000. Advance Rs. 200,000. Valid 21 Sep 2025-31 Dec 2026. Capacity Sherwood 60-120."}, {"id": "bh-menu", "title": "All Inclusive Wedding Menu", "price": "9000", "details": "Per extra person. Welcome drink, 1 appetizer, 4 salads, 2 soups, 2 mains + steamed rice, 2 meats, 1 fish, 2 vegetables + dhal, papadam, 4 desserts."}, {"id": "bh-bites", "title": "Standard bites 6 kg", "price": "0", "details": "Included combo: devilled chicken, pepper pork, fries, jumbo sausages, sauteed vegetables. Extra kg 10% off: chicken 6500, pork 7200, fish 8500, prawns 8500, fries 4000, sausages 5000, cuttlefish 8500, veg 3000."}, {"id": "bh-photo-extra", "title": "Photography extras", "price": "8000", "details": "Album page 8000, family album 25000, edited image 100, thanking card 160, extra video camera 25000, slideshow 15000, on-location trailer 20000, 12x18 frame 6500, 16x24 13750, 20x30 16500."}], "quotationPdf": null, "categories": ["Venue & Res. Halls", "Caters"], "districts": ["Kalutara"]}', 4.7, 1, 'inquiries@barnhouse.lk');
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-06', 'Courtyard by Marriott Colombo', 'Venue & Res. Halls', 'Colombo 02', 'Colombo', '1782600-3512000', 'City wedding venue at 137 Muttiah Road, Colombo 02, beside Colombo City Centre, Beira Lake and Gangaramaya. Silver to Diamond dinner packages 150-200 pax. Includes venue hire, complimentary dressing room, honeymoon B&B stay, pool and gym, photoshoot locations, corkage waived. Emerald Ballroom banquet about 150. Sales: Theerni Weerabandhu +94 74 202 0087.', '{"images": [], "quotations": [{"id": "cy-silver-26", "title": "Silver Dinner 2026 (nett pp)", "price": "11884", "details": "22 dishes. Welcome drink, 1 soup, 2 appetizers, 4 salads. Published 8844++. Min 150 / max 200 pax. Corkage waived."}, {"id": "cy-gold-26", "title": "Gold Dinner 2026 (nett pp)", "price": "12948", "details": "26 dishes including seafood. Published 9636++."}, {"id": "cy-plat-26", "title": "Platinum Dinner 2026 (nett pp)", "price": "14722", "details": "31 dishes including mutton. Published 10956++."}, {"id": "cy-dia-26", "title": "Diamond Dinner 2026 (nett pp)", "price": "15964", "details": "36 dishes. Published 11880++."}, {"id": "cy-silver-27", "title": "Silver Dinner 2027 (nett pp)", "price": "13073", "details": "Same 22-dish grid. Published 9728++. Valid till Nov 2027."}, {"id": "cy-gold-27", "title": "Gold Dinner 2027 (nett pp)", "price": "14243", "details": "Published 10599++."}, {"id": "cy-plat-27", "title": "Platinum Dinner 2027 (nett pp)", "price": "16194", "details": "Published 12051++."}, {"id": "cy-dia-27", "title": "Diamond Dinner 2027 (nett pp)", "price": "17560", "details": "Published 13068++."}], "quotationPdf": null, "categories": ["Venue & Res. Halls", "Caters"], "districts": ["Colombo"]}', 4.8, 1, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-07', 'Hotel Canterbury', 'Venue & Res. Halls', 'Colombo', 'Colombo', '5750-9750', 'Banquet wedding menus billed per person plus taxes. Bronze, Silver and Gold selections with Canterbury signature dishes, kottu, biryani and action stations on Gold.', '{"images": [], "quotations": [{"id": "can-br", "title": "Bronze Selection Menu", "price": "5750", "details": "Per person ++. 1 welcome drink, 2 appetizers, 4 salads, soup, special rice, steamed rice, noodle/pasta/kottu, chicken, seafood, pork, 4 vegetables, 4 desserts."}, {"id": "can-sv", "title": "Silver Selection Menu", "price": "7750", "details": "Per person ++. Adds biryani, prawns, extra salads and desserts."}, {"id": "can-gd", "title": "Gold Selection Menu", "price": "9750", "details": "Per person ++. Adds mutton, action station, 7 salads and 7 desserts."}], "quotationPdf": null, "categories": ["Venue & Res. Halls", "Caters"], "districts": ["Colombo"]}', 4.5, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-08', 'Asliya Golden Cassandra Lotus Ballroom', 'Venue & Res. Halls', 'Kurunegala', 'Kurunegala', '200000-800000', 'Lotus Ballroom Gold Package 2026 at Asliya Golden Cassandra, Dambokka. Full banquet menu with welcome drinks, two soups, appetizers and eight salads.', '{"images": [], "quotations": [{"id": "agc-gold", "title": "Lotus Ballroom Gold Package 2026", "price": "", "details": "Gold banquet menu: 1 welcome drink, 2 soups, 1 appetizer, 8 salads plus mains. Contact hotel for 2026 function rates."}], "quotationPdf": null, "categories": ["Venue & Res. Halls", "Caters"], "districts": ["Kurunegala"]}', 4.5, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-09', 'Opal Rich Luxury Banquet & Hotel', 'Venue & Res. Halls', 'Ganemulla', 'Gampaha', '540000-1080000', 'Ganemulla banquet hotel for 150-300 guests. Classic package at Rs. 3,600 per person includes AC hall, decorations, Ashtaka, Jayamangala Gatha, Kandyan dancers, DJ, bites and bar service.', '{"images": [], "quotations": [{"id": "or-classic", "title": "Classic Package (per person)", "price": "3600", "details": "For 150-300 pax. Settee, poruwa, table and entrance deco, oil lamp, Ashtaka, Jayamangala Gatha, Kandyan dancers, 4 bites, milk/champagne fountain, DJ, AC hall 5-6 hours, bar, digital dance floor, parking."}], "quotationPdf": null, "categories": ["Venue & Res. Halls", "Caters"], "districts": ["Gampaha"]}', 4.6, 1, 'opalrichbanquet@gmail.com');
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-10', 'Bolagala Floating Resort', 'Venue & Res. Halls', 'Katana', 'Gampaha', '130000-200000', 'Honeymoon water-cabana packages on full board, with hotel and Gami Gama photoshoot locations, candlelit island or boat dinners.', '{"images": [], "quotations": [{"id": "bf-sv", "title": "Silver Honeymoon", "price": "130000", "details": "Decorated premium water cabana full board, fruit basket, 500g cake, in-hotel photoshoot."}, {"id": "bf-gd", "title": "Gold Honeymoon", "price": "170000", "details": "Adds wine and nibbles, 5-course island candlelit dinner, Gami Gama shoot, 15% off first anniversary dinner."}, {"id": "bf-pt", "title": "Platinum Honeymoon", "price": "200000", "details": "Adds cocktails, 6-course boat dinner with sparkling wine and violinist, 15% off anniversary room."}], "quotationPdf": null, "categories": ["Venue & Res. Halls"], "districts": ["Gampaha"]}', 4.6, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-11', 'Royal Classic Nature Resort', 'Venue & Res. Halls', 'Kandy', 'Kandy', '200000-800000', 'Nature resort in Kandy for weddings and events, with a 2026 banquet menu. Sales: sales@royalclassicresort.com.', '{"images": [], "quotations": [{"id": "rc-menu", "title": "Wedding & Events Menu 2026", "price": "", "details": "Banquet menu available on request. Luxury nature-resort setting in Kandy."}], "quotationPdf": null, "categories": ["Venue & Res. Halls", "Caters"], "districts": ["Kandy"]}', 4.5, 0, 'sales@royalclassicresort.com');
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-12', 'Green Valley Resort', 'Venue & Res. Halls', 'Colombo', 'Colombo', '3550-5800', 'Banquet halls Prince and Anjelo with a dedicated wedding banquet menu from Rs. 3,550 to Rs. 5,800 per person depending on guest count.', '{"images": [], "quotations": [{"id": "gv-3550", "title": "Banquet menu from Rs. 3,550 pp", "price": "3550", "details": "Prince & Anjelo halls. Lower-count banquet rate."}, {"id": "gv-4250", "title": "Banquet menu Rs. 4,250 pp", "price": "4250", "details": "Mid banquet selection."}, {"id": "gv-4750", "title": "Banquet menu Rs. 4,750 pp (150-200 pax)", "price": "4750", "details": "150-200 packs rate."}, {"id": "gv-5250", "title": "Banquet menu Rs. 5,250 pp", "price": "5250", "details": "Includes chocolate mousse dessert option."}, {"id": "gv-5300", "title": "Banquet menu Rs. 5,300 pp (above 200 pax)", "price": "5300", "details": "Above 200 packs."}, {"id": "gv-5800", "title": "Banquet menu Rs. 5,800 pp", "price": "5800", "details": "Top printed banquet rate."}, {"id": "gv-bites", "title": "Proposed bite menu (net per kg)", "price": "3850", "details": "Devilled chicken 3850, beef 6250, pork 4250, prawns 7750, cuttlefish 6250, mutton 7850, fish 6750, sausages 3500, chickpea 2950, fries 4250. Soft drinks 150-550."}], "quotationPdf": null, "categories": ["Venue & Res. Halls", "Caters"], "districts": ["Colombo"]}', 4.4, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-13', 'Kashyapa Royal Knot', 'Venue & Res. Halls', 'Colombo', 'Colombo', '200000-800000', 'Full wedding coordination package: Kandyan dancing, Ashtaka, Jayamangala Gatha, complete decorations, DJ, bites by guest count, BMW wedding car, honeymoon destination and event planning. Menu is the Royal Knot banquet.', '{"images": [], "quotations": [{"id": "krk-pkg", "title": "Royal Knot Complete Event Package", "price": "", "details": "Decoration, dancers, DJ, bites (4-18 kg by pax), soft drinks, BMW wedding car, honeymoon destination, indoor/outdoor photo locations. Pricing by guest count on request."}], "quotationPdf": null, "categories": ["Venue & Res. Halls", "Caters", "Floral & Deco"], "districts": ["Colombo"]}', 4.5, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-14', 'Everluxe Stories Photography', 'Photography & Videography', 'Colombo', 'Colombo', '25000-260000', 'Lead photographer Pasidu Wasala Pathmasiri. Full 2026 investment guide: 5 engagement, 4 one-day and 4 two-day wedding packages with or without pre-shoot. 25% non-refundable advance. No raw files. Call 078 510 4488.', '{"images": [], "quotations": [{"id": "ev-eng1", "title": "Engagement Package 01", "price": "25000", "details": "Engagement shoot only, all edited soft copies."}, {"id": "ev-eng2", "title": "Engagement Package 02", "price": "40000", "details": "Shoot, registration and ceremony, all edited soft copies."}, {"id": "ev-eng3", "title": "Engagement Package 03", "price": "60000", "details": "Adds 2x 16x24 enlargements."}, {"id": "ev-eng4", "title": "Engagement Package 04", "price": "85000", "details": "Adds 8x24 30-page album."}, {"id": "ev-eng5", "title": "Engagement Package 05", "price": "100000", "details": "Adds 100 thank-you cards."}, {"id": "ev-1d1", "title": "One Day Wedding without Pre-shoot 01", "price": "75000", "details": "Morning + ceremony, all edited soft copies."}, {"id": "ev-1d2", "title": "One Day Wedding without Pre-shoot 02", "price": "100000", "details": "Adds 2 enlargements and 100 cards."}, {"id": "ev-1d3", "title": "One Day Wedding without Pre-shoot 03", "price": "125000", "details": "Adds 30-page album and 150 cards."}, {"id": "ev-1d4", "title": "One Day Wedding without Pre-shoot 04", "price": "150000", "details": "Album plus 200 cards."}, {"id": "ev-1dp1", "title": "One Day Wedding with Pre-shoot 01", "price": "100000", "details": "Pre-shoot, morning, ceremony, 100 cards."}, {"id": "ev-1dp4", "title": "One Day Wedding with Pre-shoot 04", "price": "175000", "details": "2 enlargements, 30-page album, 250 cards."}, {"id": "ev-2d1", "title": "Two Day Wedding without Pre-shoot 01", "price": "140000", "details": "Homecoming + wedding day, 100 cards."}, {"id": "ev-2d4", "title": "Two Day Wedding without Pre-shoot 04", "price": "230000", "details": "4 enlargements, 12x36 60-page luxury album, 250 cards."}, {"id": "ev-2dp1", "title": "Two Day Wedding with Pre-shoot 01", "price": "170000", "details": "Pre-shoot, homecoming, wedding, 100 cards."}, {"id": "ev-2dp4", "title": "Two Day Wedding with Pre-shoot 04", "price": "260000", "details": "4 enlargements, 12x36 60-page luxury album, 250 cards."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.7, 1, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-15', 'DI Photography', 'Photography & Videography', 'Colombo', 'Colombo', '30000-180000', 'Lume Weddings / DI Photography. Wedding, homecoming, engagement, pre-shoot and videography 2025/26. Transport extra outside Western Province. 20% non-refundable advance. +94 71 403 6058.', '{"images": [], "quotations": [{"id": "di-wed-lo", "title": "Wedding photography from", "price": "75000", "details": "Wedding packages Rs. 75,000 / 110,000 / 140,000 / 180,000."}, {"id": "di-wed-hi", "title": "Wedding photography top", "price": "180000", "details": "Highest printed wedding photography rate."}, {"id": "di-hc-sv", "title": "Homecoming Silver", "price": "35000", "details": "Main session + ceremony, up to 8 hours, two photographers, 150 edited images, all unedited. Session-only Rs. 30,000."}, {"id": "di-hc-gd", "title": "Homecoming Gold", "price": "85000", "details": "Adds 50-page 10x24 album, 16x24 framed enlargement, 100 thank-you cards."}, {"id": "di-eng-sv", "title": "Engagement Silver", "price": "40000", "details": "6 hours, preferred location + ceremony, 100 edited images."}, {"id": "di-eng-gd", "title": "Engagement Gold", "price": "65000", "details": "8 hours, 40-page 10x24 album, 150 edited images."}, {"id": "di-pre-sv", "title": "Pre-shoot Silver", "price": "30000", "details": "6 hours casual, 100 edited images."}, {"id": "di-pre-gd", "title": "Pre-shoot Gold", "price": "45000", "details": "Adds 30-page 12x18 album."}, {"id": "di-vid-cer1", "title": "Videography wedding ceremony 1 cam", "price": "40000", "details": "3-5 min trailer + 45-60 min full HD."}, {"id": "di-vid-cer2", "title": "Videography wedding ceremony 2 cam", "price": "65000", "details": "Two cameras. 4K extra 20,000. Drone extra 20,000."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.6, 0, 'disalgeelaka2@gmail.com');
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-16', 'Artsy Romance', 'Photography & Videography', 'Colombo', 'Colombo', '30000-260000', 'Artsy Romance - Two Hearts, One Journey. Full 2026 price guide: wedding Bronze-Gold, homecoming, pre-shoot, engagement and all-in-one Platinum. Rs. 15,000 non-refundable advance. Travel extra outside Colombo.', '{"images": [], "quotations": [{"id": "ar-br", "title": "Wedding Bronze", "price": "80000", "details": "Preferred-location session, ceremony and reception, two cameras, all retouched files. Also listed at Rs. 100,000."}, {"id": "ar-sv", "title": "Wedding Silver", "price": "125000", "details": "Adds 12x30 40-page album, 16x24 + 12x18 enlargements, 100 cards. Also listed at Rs. 145,000."}, {"id": "ar-gd", "title": "Wedding Gold", "price": "150000", "details": "Adds getting-ready coverage and 60-page album, 150 cards. Also listed at Rs. 170,000."}, {"id": "ar-hc-br", "title": "Homecoming Bronze", "price": "50000", "details": "Session + ceremony, retouched files. Also listed at Rs. 65,000."}, {"id": "ar-hc-sv", "title": "Homecoming Silver", "price": "80000", "details": "Adds 10x24 30-page album and 12x18 enlargement. Also listed at Rs. 95,000."}, {"id": "ar-pre-br", "title": "Pre-shoot Bronze", "price": "30000", "details": "3 hours, one location. Also listed at Rs. 40,000."}, {"id": "ar-pre-sv", "title": "Pre-shoot Silver", "price": "45000", "details": "6 hours, two locations, two outfits. Also listed at Rs. 60,000."}, {"id": "ar-pt1", "title": "All-in-One Platinum I", "price": "200000", "details": "Pre-shoot, wedding, homecoming, 60-page album. Also listed at Rs. 220,000."}, {"id": "ar-pt2", "title": "All-in-One Platinum II", "price": "240000", "details": "Two-location pre-shoot, getting ready, wedding, homecoming, two albums. Also listed at Rs. 260,000."}, {"id": "ar-eng-br", "title": "Engagement Bronze", "price": "45000", "details": "Session + ceremony. Also listed at Rs. 60,000."}, {"id": "ar-eng-sv", "title": "Engagement Silver", "price": "80000", "details": "Adds 10x24 album and 12x18 enlargement. Also listed at Rs. 95,000."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.6, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-17', 'Romance Wedding Photography', 'Photography & Videography', 'Colombo', 'Colombo', '155000-595000', 'Romance Wedding Photography 2026-2027. Wedding-only, wedding+pre-shoot and three-event collections from Rs. 155,000 to Rs. 595,000. Call 077 11 77 513 / info.romancelk@gmail.com. Rs. 30,000 non-refundable advance.', '{"images": [], "quotations": [{"id": "rwp-begin", "title": "The Beginning", "price": "155000", "details": "Up to 10 hours, getting ready, portraits, ceremony and reception, 2 photographers, 150 edited + all unedited."}, {"id": "rwp-eternal", "title": "Eternal Story", "price": "195000", "details": "10 hours, 10x24 50-page story book, two 16x24 frames, 200 edited."}, {"id": "rwp-sig", "title": "Signature Story", "price": "265000", "details": "12 hours, 3 photographers, 12x24 60-page book, family album, four 16x24 frames, 300 edited, 100 cards."}, {"id": "rwp-forever", "title": "Forever Story", "price": "385000", "details": "12 hours, 4 photographers, 12x30 book, family + memory books, 20x30 and 16x24 frames, 400 edited, 150 photobooth cards, 5 reels."}, {"id": "rwp-time", "title": "Timeless Collection (wedding + pre)", "price": "255000", "details": "3-hour pre + 10-hour wedding, 12x24 50-page book."}, {"id": "rwp-eleg", "title": "Elegance Collection (most popular)", "price": "295000", "details": "4-hour pre + 12-hour wedding, 3 photographers, pre-shoot album."}, {"id": "rwp-ivory", "title": "Ivory Collection", "price": "365000", "details": "Adds family album and four 16x24 frames, 400 edited."}, {"id": "rwp-luxe", "title": "Luxe Collection", "price": "495000", "details": "5-hour pre, 4 photographers, 20x30 frames, 500 edited, 5 reels."}, {"id": "rwp-ever", "title": "Evermore Chapter ( + homecoming)", "price": "295000", "details": "Pre + wedding + homecoming shoot only."}, {"id": "rwp-amour", "title": "Amour Chapter", "price": "365000", "details": "4-hour pre, 8-hour homecoming, 12-hour wedding."}, {"id": "rwp-noble", "title": "Noble Chapter", "price": "445000", "details": "Full three-event coverage."}, {"id": "rwp-rom", "title": "Romance Chapter", "price": "595000", "details": "Top wedding + pre + homecoming collection."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.8, 1, 'info.romancelk@gmail.com');
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-18', 'Ring Tales', 'Photography & Videography', 'Colombo', 'Colombo', '35000-140000', 'Videography-only studio for 2026-2027. Wedding films, reels, engagements, homecomings and casual shoots. Rs. 15,000 non-refundable advance. Travel extra outside Colombo. +94 766 675 545 / +94 715 355 545. @ring.tales.films.', '{"images": [], "quotations": [{"id": "rt-1", "title": "Package 1 (minimal wedding)", "price": "60000", "details": "10 hrs, 1 HD camera, 3-5 min trailer, web delivery."}, {"id": "rt-2", "title": "Package 2", "price": "85000", "details": "10 hrs, 2 cameras, trailer + 15-20 min summary."}, {"id": "rt-3", "title": "Package 3", "price": "100000", "details": "10 hrs, 2 cameras, trailer + up to 60 min full video."}, {"id": "rt-4", "title": "Package 4", "price": "140000", "details": "12 hrs, 3 cameras, trailer + 60 min full video."}, {"id": "rt-reels", "title": "Content package - reels / TikTok", "price": "35000", "details": "10 hrs mirrorless, 3 reels up to 1 min each."}, {"id": "rt-eng1", "title": "Engagements & homecomings 1", "price": "50000", "details": "6 hrs, 1 camera, up to 20 min summary."}, {"id": "rt-eng2", "title": "Engagements & homecomings 2", "price": "75000", "details": "8 hrs, 2 cameras, up to 30 min summary."}, {"id": "rt-cas1", "title": "Casual shoot 1", "price": "40000", "details": "4 hrs, 1 camera, 2-5 min cinematic."}, {"id": "rt-cas2", "title": "Casual shoot 2", "price": "55000", "details": "4 hrs, 2 cameras, 2-5 min cinematic."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.7, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-19', 'Kalana Ashan Photography', 'Photography & Videography', 'Colombo', 'Colombo', '160000-160000', '2026 wedding photography. Lite package covers getting ready, 10-hour ceremony and reception, 40-page album and framed portraits.', '{"images": [], "quotations": [{"id": "ka-lite", "title": "Lite Wedding Package", "price": "160000", "details": "Main session, 10-hour ceremony and reception, bride and groom getting ready, 10x24 album 40 pages, two 16x24 framed portraits, 150 edited images, all unedited on USB."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.6, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-20', 'Lakmal Sinharage Wedding Studio', 'Photography & Videography', 'Colombo', 'Colombo', '300000-300000', 'Traditional wedding photography studio. 2026-2027 A-Group package with 10-hour coverage and magazine album.', '{"images": [], "quotations": [{"id": "ls-a", "title": "A-Group Wedding Package", "price": "300000", "details": "10x24 magazine album 40 pages, 100 thank-you cards, one 12x18 enlargement, 10 hours exclusive coverage, high-res soft copies."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.5, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-21', 'Erosveil', 'Photography & Videography', 'Colombo', 'Colombo', '76500-123000', '2026 wedding photography with a 15% offer. Relaxed, candid style. Packages include ceremony coverage, albums and thank-you cards.', '{"images": [], "quotations": [{"id": "er-1", "title": "Wedding Package 01", "price": "76500", "details": "Offer price (was Rs. 90,000). Main session, ceremony, 16x24 enlargement, 50 thank-you cards."}, {"id": "er-2", "title": "Wedding Package 02", "price": "102000", "details": "Offer price (was Rs. 120,000). Two photographers, 40-page album, 2 enlargements, 100 cards."}, {"id": "er-3", "title": "Wedding Package 03", "price": "123000", "details": "Offer price (was Rs. 145,000). 50-page album, 3 enlargements, 150 cards."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.6, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-22', 'Myrrah Weddings', 'Photography & Videography', 'Colombo', 'Colombo', '120000-250000', 'Weddings by Lasith Jayawardane. 2026-2027 photography and cinematography. Free transport in Colombo.', '{"images": [], "quotations": [{"id": "my-straw", "title": "Strawberry Package", "price": "125000", "details": "Main session, ceremony, reception, 200 edits, 10x20 album 40 pages, two 12x18 frames, 60 cards."}, {"id": "my-black", "title": "Blackberry Package", "price": "150000", "details": "250 edits, 12x30 album, two 16x24 frames, 100 cards."}, {"id": "my-rasp", "title": "Raspberry Package", "price": "220000", "details": "300 edits, wedding plus family albums, four frames, 150 cards."}, {"id": "my-aio", "title": "All In One Photo + Video", "price": "250000", "details": "10-hour wedding photography with 3 photographers, 2-camera film, 2-hour pre-shoot."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.7, 1, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-23', 'Authetic Weddings', 'Photography & Videography', 'Colombo', 'Colombo', '40000-70000', 'Wedding studio price guide 2026-2027 for casual, wedding, homecoming and engagement sessions.', '{"images": [], "quotations": [{"id": "aw-basic", "title": "Casual Session Basic", "price": "40000", "details": "6 hours, preferred location, 100 edited images, 2 outfits, all soft copies."}, {"id": "aw-std", "title": "Casual Session Standard", "price": "70000", "details": "Adds 8x20 magazine album 30 pages."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.5, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-24', 'Autumn Feel by Ashen Eranda', 'Photography & Videography', 'Colombo', 'Colombo', '100000-500000', 'Ashen Eranda photography. Over 5 years wedding work and 8 years retouching. 2026-2027 guide covering wedding, homecoming and engagement.', '{"images": [], "quotations": [{"id": "af-guide", "title": "2026-2027 Price Guide", "price": "", "details": "Wedding, homecoming and engagement collections. See attached price guide for current package rates."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.6, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-25', 'Leemondo', 'Photography & Videography', 'Colombo', 'Colombo', '100000-500000', 'Memories last forever. Wedding, homecoming and engagement price guide 2025-2026 / 2026-2027.', '{"images": [], "quotations": [{"id": "lm-guide", "title": "Wedding / Homecoming & Engagement Guide", "price": "", "details": "See 2026-2027 price guide for package rates."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.5, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-26', 'Velvet Ceylon', 'Photography & Videography', 'Colombo', 'Colombo', '100000-500000', 'Weddings, cinematic films and storytelling. Traditional Kandyan and modern western coverage across Sri Lanka.', '{"images": [], "quotations": [{"id": "vc-guide", "title": "Wedding Photography & Film Packages", "price": "", "details": "See package guide for current cinematography and photography rates."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.7, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-27', 'Danushka Senadeera Photography', 'Photography & Videography', 'Colombo', 'Colombo', '350000-350000', 'Price guide 2025-2026. Bronze Classic covers getting ready, main shoot, ceremony and reception with photobook and slideshow.', '{"images": [], "quotations": [{"id": "ds-bronze", "title": "Bronze Classic Package", "price": "350000", "details": "Bride and groom getting ready, main shoot, ceremony and reception, 6 prints 12x18, one framed 12x18, 16x24 photobook, slideshow."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.8, 1, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-28', 'Studio Fantasy', 'Photography & Videography', 'Colombo', 'Colombo', '45000-60000', '2026-2027 photography and cinematography. Engagement packages with enlargements, album options and video reels.', '{"images": [], "quotations": [{"id": "sf-e1", "title": "Engagement Package I", "price": "45000", "details": "12x18 enlargement, engagement video reel, all high-res images."}, {"id": "sf-e2", "title": "Engagement Package II", "price": "60000", "details": "08x24 magazine album 20 pages, 10x15 enlargement, reel, all high-res images."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.5, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-29', 'Warmly Weddings', 'Photography & Videography', 'Colombo', 'Colombo', '150000-190000', 'Storytelling wedding photography for 2026-2027. Bronze and Silver 12-hour wedding packages with two photographers.', '{"images": [], "quotations": [{"id": "ww-br", "title": "Bronze Wedding Package", "price": "150000", "details": "12 hours, main session, ceremony and reception, two 16x24 frames, 200 edited images, two photographers."}, {"id": "ww-sv", "title": "Silver Wedding Package", "price": "190000", "details": "Adds getting-ready coverage, 10x24 50-page album, 100 thanking cards."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.6, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-30', 'Madushan Udayanga Photography', 'Photography & Videography', 'Pannipitiya', 'Colombo', '90000-190000', 'Pannipitiya and Meegoda studio. 2026-2027 wedding, pre-shoot and homecoming photo/video packages from Rs. 90,000 to Rs. 190,000. 071 578 0244 / 077 573 4188 / 011 708 0165.', '{"images": [], "quotations": [{"id": "mu-reel", "title": "Wedding + video reel", "price": "90000", "details": "One-day coverage, wedding reel, 16x24 60-page magazine album, two 20x30 framed enlargements, 100 thank cards 6x8, all soft copies."}, {"id": "mu-gold", "title": "Golden Package 2026-2027", "price": "100000", "details": "Wedding + pre-shoot photo and video. 30x12 60-page album, two 24x16 frames, 100 cards, wedding + pre reels and animation, all soft copies."}, {"id": "mu-plat", "title": "Platinum Package", "price": "135000", "details": "Wedding + homecoming photo and video (printed flyer rate)."}, {"id": "mu-dia", "title": "Diamond Package 2026-2027", "price": "190000", "details": "Wedding + homecoming + pre-shoot photo and video. Full HD recap videos, 30x12 60-page + 20x8 20-page albums, 20x30 and 24x16 frames (2 each), 150 cards, pre-shoot animation, all soft copies."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.5, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-31', 'Shan Jayasinghe Photography', 'Photography & Videography', 'Colombo', 'Colombo', '100000-500000', '2026 wedding packages. Capture the art of your love story.', '{"images": [], "quotations": [{"id": "sj-2026", "title": "2026 Wedding Packages", "price": "", "details": "See 2026 wedding package guide. Facebook: Shan Jayasinghe Photography."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.5, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-32', 'Bright Room', 'Photography & Videography', 'Kadawatha', 'Gampaha', '20000-135000', 'Kadawatha studio at No. 513/2/C, Ihalabiyanwila. Casual, convocation, engagement and Bronze-Platinum wedding packages. Packages can be customised. 076 291 0122 / studiobrightRoom112@gmail.com.', '{"images": [], "quotations": [{"id": "br-cas", "title": "Casual / convocation from", "price": "20000", "details": "Customisable Kadawatha studio sessions."}, {"id": "br-eng", "title": "Engagement", "price": "30000", "details": "Morning session 40 soft copies, morning reel, function coverage."}, {"id": "br-wed-br", "title": "Wedding Bronze", "price": "35000", "details": "Morning session 40 soft copies + reel, thank-you card soft copy, wedding-day coverage, 1 photographer."}, {"id": "br-wed-sv", "title": "Wedding Silver", "price": "75000", "details": "Pre-shoot 40 copies + 30s reel, morning session, coverage, 16x24 30-page album, 1 photographer."}, {"id": "br-wed-gd", "title": "Wedding Gold", "price": "105000", "details": "Pre-shoot, morning, coverage, 30-page album, 100 thank-you cards, 2 photographers, 1 enlargement."}, {"id": "br-wed-pt", "title": "Wedding Platinum", "price": "135000", "details": "Pre-shoot, 40-page album, 150 cards, 2 photographers, 2 enlargements."}, {"id": "br-vid", "title": "Videography wedding day", "price": "45000", "details": "Wedding-day video coverage. Pre-shoot cinematic Rs. 35,000."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Gampaha"]}', 4.4, 0, 'studiobrightRoom112@gmail.com');
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-33', 'Mark Event Planner', 'Floral & Deco', 'Colombo', 'Colombo', '30000-30000', 'Deco by Mark. Home-function decoration package covering entrance, settee back and oil lamp. Limited offer.', '{"images": [], "quotations": [{"id": "mk-home", "title": "Home Function Decorations Package", "price": "30000", "details": "Entrance decoration, settee back and oil lamp decoration. Limited offer."}], "quotationPdf": null, "categories": ["Floral & Deco"], "districts": ["Colombo"]}', 4.5, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-34', 'Clover Banquets & Resorts', 'Venue & Res. Halls', 'Kelaniya', 'Gampaha', '5800-9200', 'Wedding menus 2026 at Emerald, Gold and Crystal banquets (50-800 pax), Gonawala, Kelaniya. Handwritten rates valid till 31 July: Silver 5,800, Platinum 6,100, Royal 9,200 nett per person. Printed validity to 31 Dec 2026. Contact Kushan A. Mendis 076 282 0606.', '{"images": [], "quotations": [{"id": "cl-sv", "title": "Silver Menu (Emerald & Gold, 150-800 pax)", "price": "5800", "details": "Nett per person. Handwritten rate."}, {"id": "cl-pt", "title": "Platinum Menu (Emerald & Gold, 150-800 pax)", "price": "6100", "details": "Nett per person. Dessert bar / milk powder complimentary noted."}, {"id": "cl-ry", "title": "Royal Menu (Emerald & Gold, 150-800 pax)", "price": "9200", "details": "Nett per person."}, {"id": "cl-cr", "title": "Crystal Menu (50-100 pax)", "price": "", "details": "From a quoted nett per person. Intimate Crystal Banquet."}, {"id": "cl-bites", "title": "Bites and live stations", "price": "100", "details": "Bites net/kg: chicken 3550, prawns 5800, fish 6000, pork 6300, sausages 3600, chickpeas 1800, fried chicken 3900, fried fish 6300, cuttlefish 4200, fries 4000, boiled veg 2100, cutlet 100. Live stations 300-650 pp. Iced coffee 375. Soft drinks 300-700."}], "quotationPdf": null, "categories": ["Venue & Res. Halls", "Caters"], "districts": ["Gampaha"]}', 4.7, 1, 'info@cloverbanquets.com');
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-35', 'Pegasus Reef Hotel', 'Venue & Res. Halls', 'Wattala', 'Gampaha', '200000-800000', 'City resort at Hendala, Wattala. Wedding package with welcome drinks, international cuisine, photo locations, complimentary changing room, oil lamp, podium, bandstand, dance floor, registration/gift/sashreeka/cake tables. Book 200+ guests and 20 guests are free; 150+ guests get 2 changing rooms. Honeymoon 20% off 2nd night. Offers valid for bookings before 31 Aug 2026.', '{"images": [], "quotations": [{"id": "pg-wed", "title": "Wedding package inclusions", "price": "", "details": "Welcome drinks, international cuisine, photo locations, complimentary changing room. 150+ pax: honeymoon HB room. 250+ pax: 1st anniversary dinner voucher. 300+ pax: sparkling wine, fruit basket and chocolates. Food tasting for 3. Pre-shoot location. Pool and gym for the couple."}, {"id": "pg-offer", "title": "200+ guests offer", "price": "0", "details": "20 guests hosted free when booking 200 or more. Two complimentary changing rooms from 150 guests."}, {"id": "pg-hn", "title": "Honeymoon escape", "price": "", "details": "Photo locations, romantic room decoration, premium chocolate box, heart-shaped milk rice breakfast, couple gift. 20% off 2nd night."}], "quotationPdf": null, "categories": ["Venue & Res. Halls", "Caters"], "districts": ["Gampaha"]}', 4.7, 1, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-36', 'Seethawaka Regency', 'Venue & Res. Halls', 'Avissawella', 'Colombo', '200000-2000000', 'Luxury hotel and iconic wedding venue with 12+ years. All-inclusive 2026-2027 Silver, Gold, Platinum and Regency packages: grand buffet, floral decorations, entertainment, wedding cake, luxury wedding car, bites and soft drinks. Halls: Grand Ballroom 400, Diamond Ballroom 250, Golden Court 50, Kings Pool Side 75, outdoor garden/pool 200.', '{"images": [], "quotations": [{"id": "sr-sv", "title": "Silver all-inclusive 2026-2027", "price": "", "details": "Grand buffet, floral decorations, entertainment, cake, luxury wedding car, bites and soft drinks."}, {"id": "sr-gd", "title": "Gold all-inclusive 2026-2027", "price": "", "details": "Higher-tier buffet and ceremony inclusions."}, {"id": "sr-pt", "title": "Platinum all-inclusive 2026-2027", "price": "", "details": "Premium all-inclusive celebration."}, {"id": "sr-rg", "title": "Regency all-inclusive 2026-2027", "price": "", "details": "Top exclusive Regency service package."}, {"id": "sr-halls", "title": "Signature venues", "price": "0", "details": "Grand Ballroom 400 pax, Diamond Ballroom 250 (20m chandelier), Golden Court 50, Kings Pool Side 75, outdoor garden and pool 200."}], "quotationPdf": null, "categories": ["Venue & Res. Halls", "Caters"], "districts": ["Colombo"]}', 4.8, 1, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-37', 'The Blue Water Hotel and Spa', 'Venue & Res. Halls', 'Wadduwa', 'Kalutara', '9185-12445', 'Ocean-view weddings. Magical Weddings menu options 01-03 billed per person plus 10% service charge and government taxes.', '{"images": [], "quotations": [{"id": "bw-1", "title": "Option 01", "price": "9185", "details": "++ 10% SC + tax. 6 appetizers/salads, 1 soup, 3 rice/noodles/pasta, fish, seafood live, chicken, pork, mutton or beef, 3 veg, 5 desserts."}, {"id": "bw-2", "title": "Option 02", "price": "10850", "details": "++. 7 appetizers/salads + salad action, 4 rice/noodles/pasta, 6 desserts."}, {"id": "bw-3", "title": "Option 03", "price": "12445", "details": "++. 9 appetizers/salads, prawn live, mutton or lamb, 4 veg, 7 desserts. Pork/beef can upgrade to carvery."}], "quotationPdf": null, "categories": ["Venue & Res. Halls", "Caters"], "districts": ["Kalutara"]}', 4.8, 1, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-38', 'Grand Mondo Luxury Banquets', 'Venue & Res. Halls', 'Homagama', 'Colombo', '380000-1900000', 'Panaluwa, Watareka banquet hotel. All-inclusive wedding package Rs. 380,000 net covers decorations, traditional ceremony team, DJ, LED wall, 2-hour open bar, 15 kg bites, wedding car 10 hrs/30 km. Gold menu noted at 6,219 x 200 pax. Platinum menu Rs. 8,500 and Diamond Rs. 9,500.', '{"images": [], "quotations": [{"id": "gmd-all", "title": "All Inclusive Wedding Package", "price": "380000", "details": "Flower decorations, settee, traditional fittings, oil lamp, milk or champagne fountain, cake starch or Saubagya, Ashtaka, Jayamangala Gatha (3 girls), dancing or Indian drums, DJ + lights + smoke, LED wall, Salupaliya or Western dance, 2-hour open bar, 15 kg cooked bites, photo location, morning tea, event manager, 2 changing rooms, wedding car (Benz/BMW/Defender/Audi) 10 hrs 30 km with deco. Free service charge and electricity."}, {"id": "gmd-gold", "title": "Gold menu 200 pax (handwritten)", "price": "1243800", "details": "Gold menu 6,219 x 200 noted on flyer, plus 330,000 ceremony extras."}, {"id": "gmd-pt", "title": "Platinum Menu", "price": "8500", "details": "Per person. 1 welcome drink, 1 hot pot, 7 salads, 3 rice, 1 noodles/pasta, 5 veg, 3 meat/seafood, 8 desserts. 38 varieties."}, {"id": "gmd-dia", "title": "Diamond Menu", "price": "9500", "details": "Per person. 2 hot pots, 9 salads, 3 rice, 2 noodles/pasta, 6 veg, 4 meat/seafood, 9 desserts. 48 varieties."}], "quotationPdf": null, "categories": ["Venue & Res. Halls", "Caters", "Floral & Deco"], "districts": ["Colombo"]}', 4.7, 1, 'grandmondobanquet@gmail.com');
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-39', 'AVANI Kalutara Resort', 'Venue & Res. Halls', 'Kalutara', 'Kalutara', '7200-300000', 'Coastal resort weddings: indoor receptions, lagoon-side ceremonies and beach. Complimentary inclusions above 120 guests. Packages Bronze-Platinum with wedding-show offers. Outdoor lagoon or river-mouth/beach hire.', '{"images": [], "quotations": [{"id": "av-br", "title": "Bronze (show offer)", "price": "7200", "details": "Without tax 6000 / with tax 8000 / show 7200. Min 120 / max 250 pax. Below 120: hall Rs. 20,000 per hour."}, {"id": "av-sv", "title": "Silver (show offer)", "price": "7785", "details": "Without tax 6500 / with tax 8650."}, {"id": "av-gd", "title": "Gold (show offer)", "price": "8550", "details": "Without tax 7150 / with tax 9500."}, {"id": "av-pt", "title": "Platinum (show offer)", "price": "9180", "details": "Without tax 7650 / with tax 10200."}, {"id": "av-lag", "title": "Outdoor full function - lagoon", "price": "150000", "details": "Poruwa-only lagoon Rs. 30,000."}, {"id": "av-beach", "title": "Outdoor full function - river mouth & beach", "price": "300000", "details": "Poruwa-only beach Rs. 60,000."}, {"id": "av-inc", "title": "Complimentary inclusions (120+ guests)", "price": "0", "details": "Welcome drink, half-board couple room, changing room, photo locations, corkage for spirits, chair covers, tablecloths, runners and bows, registration/cake/gift tables, dancing floor."}], "quotationPdf": null, "categories": ["Venue & Res. Halls", "Caters"], "districts": ["Kalutara"]}', 4.8, 1, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-40', 'Citrus Waskaduwa', 'Venue & Res. Halls', 'Waskaduwa', 'Kalutara', '200000-2000000', 'Star-class west-coast resort, 400 m beachfront, 37 km from Colombo. Beach, garden and grand ballroom weddings with dedicated planning and award-winning cuisine. Also bridal showers and bachelor parties.', '{"images": [], "quotations": [{"id": "cw-beach", "title": "Beach / garden / ballroom wedding", "price": "", "details": "Dedicated planning team, designed or custom menus. Contact via on-flyer WhatsApp QR."}, {"id": "cw-party", "title": "Bridal shower & bachelor packages", "price": "", "details": "Themed pre-wedding events at the resort."}], "quotationPdf": null, "categories": ["Venue & Res. Halls", "Caters"], "districts": ["Kalutara"]}', 4.7, 1, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-41', 'Studio Wow Images', 'Photography & Videography', 'Hungama', 'Hambantota', '95000-265000', 'Wow Images - A Hope in Every Click. Studio on Thissa Road, Hungama. Bronze to Platinum wedding photography. Ishara Madushanka.', '{"images": [], "quotations": [{"id": "wow-br1", "title": "Bronze Package 01", "price": "95000", "details": "Morning shoot, 25-image FB album, function coverage, 2x 16x24 enlargements, 100 cards, 12x18 30-page album, edited images on pen drive."}, {"id": "wow-br2", "title": "Bronze Package 02", "price": "115000", "details": "150 cards, 16x24 25-page album."}, {"id": "wow-br3", "title": "Bronze Package 03", "price": "130000", "details": "30 FB images, 4 enlargements, 16x24 30-page album, 200 cards."}, {"id": "wow-sv1", "title": "Silver Package 01", "price": "150000", "details": "Pre-shoot + morning + full day, 12x30 35-page magazine album, 150 cards, framed 20x30 and 16x24 (2 each), USB."}, {"id": "wow-sv2", "title": "Silver Package 02", "price": "175000", "details": "Pre-shoot 12x18 15-page album, 16x24 35-page wedding album, 200 cards, 4x 16x24 + 2 family enlargements."}, {"id": "wow-gd1", "title": "Gold Package 01", "price": "200000", "details": "Pre-shoot 3 dresses free, 12x18 15-page + 12x36 35-page albums, 200 cards, multiple framed enlargements, USB."}, {"id": "wow-pt1", "title": "Platinum Package 01", "price": "265000", "details": "Pre-shoot 3 dresses, 12x18 20-page + 16x24 45-page albums, 250 cards, 36x24 / 20x30 / family / group frames, USB."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Hambantota"]}', 4.6, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-42', 'Eresh Jayanga Dias Photography', 'Photography & Videography', 'Ragama', 'Gampaha', '120000-165000', 'Welisara studio. One-day wedding-only packages 01-05 with magazine albums, framed enlargements, high-res soft copies, social retouching, assistant and limited-distance transport included.', '{"images": [], "quotations": [{"id": "ej-1", "title": "Package 01 - Wedding only", "price": "120000", "details": "12x24 50-page magazine album with box, 12x18 wedding + group enlargements."}, {"id": "ej-2", "title": "Package 02 - Wedding only", "price": "130000", "details": "12x30 50-page album, 16x24 wedding + 12x18 group enlargements."}, {"id": "ej-3", "title": "Package 03 - Wedding only", "price": "145000", "details": "Adds couple 12x18 enlargement."}, {"id": "ej-4", "title": "Package 04 - Wedding only", "price": "155000", "details": "12x34 50-page album, 100 thanking cards 4x8."}, {"id": "ej-5", "title": "Package 05 - Wedding only", "price": "165000", "details": "12x34 or 17x24 album, 20x30 wedding enlargement, 100 cards 5x8."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Gampaha"]}', 4.6, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-43', 'Darshana Gehagoda Photography', 'Photography & Videography', 'Colombo', 'Colombo', '100000-500000', 'Wedding photography studio (also branded with RAY MAC photo gallery). Traditional Kandyan and modern coverage.', '{"images": [], "quotations": [{"id": "dg-wed", "title": "Wedding photography", "price": "", "details": "Portfolio coverage for Kandyan and contemporary weddings. Call for 2026 package rates."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.5, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-44', 'Kaushal Photography', 'Photography & Videography', 'Colombo', 'Colombo', '100000-500000', 'Bright outdoor wedding photography. www.kaushalphotography.lk', '{"images": [], "quotations": [{"id": "kp-wed", "title": "Wedding photography", "price": "", "details": "Natural outdoor and garden wedding coverage. Contact via website."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.6, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-45', 'Wedding Advizor', 'Floral & Deco', 'Colombo', 'Colombo', '50000-300000', 'ICOES certified planner Chathura Sandeepa. Stress-free wedding planning and day coordination. Beyond planning, like family.', '{"images": [], "quotations": [{"id": "wa-plan", "title": "Wedding planning & day coordination", "price": "", "details": "Full planning and on-the-day coordination. Contact for a custom quotation."}], "quotationPdf": null, "categories": ["Floral & Deco"], "districts": ["Colombo"]}', 4.7, 1, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-46', 'Majestic Men', 'Groom service', 'Colombo', 'Colombo', '25000-150000', 'Premium suits for the modern groom. Premium quality, perfect and elegant design.', '{"images": [], "quotations": [{"id": "mm-suit", "title": "Premium groom suit", "price": "", "details": "Custom / premium suits. Contact for fitting and 2026 rates."}], "quotationPdf": null, "categories": ["Groom service"], "districts": ["Colombo"]}', 4.5, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-47', 'Hair Avenue', 'Bridal Service', 'Moratuwa', 'Colombo', '12000-20000', 'Hair & beauty bridal salon and wedding grooming salon at Galle Road, Rawathawatta. Bridesmaid beauty packages Bronze-Platinum plus add-on nails and waxing.', '{"images": [], "quotations": [{"id": "ha-br", "title": "Bridesmaid Bronze", "price": "12000", "details": "Hairstyle, makeup, dressing."}, {"id": "ha-sv", "title": "Bridesmaid Silver", "price": "15000", "details": "Cleanup, full-face threading, hairstyle, makeup, dressing."}, {"id": "ha-gd", "title": "Bridesmaid Gold", "price": "17000", "details": "Facial, threading or wax, hairstyle, makeup, dressing."}, {"id": "ha-pt", "title": "Bridesmaid Platinum", "price": "20000", "details": "Jovees gold facial, threading or wax, hairstyle, makeup, dressing."}, {"id": "ha-add", "title": "Add-ons", "price": "1500", "details": "Manicure 2500, pedicure 3500, gel colour 1500, nail extensions 5000, arms or legs wax 3000."}, {"id": "ha-groom", "title": "Wedding grooming salon", "price": "", "details": "Men''s wedding grooming at Hair Avenue."}], "quotationPdf": null, "categories": ["Bridal Service", "Groom service"], "districts": ["Colombo"]}', 4.6, 1, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-48', 'Salon Udani Pvt Ltd', 'Bridal Service', 'Colombo', 'Colombo', '50000-200000', 'Bridal makeup, hair and traditional Kandyan dressing.', '{"images": [], "quotations": [{"id": "su-bridal", "title": "Kandyan bridal dressing", "price": "", "details": "Traditional bridal makeup, hair and Osari dressing. Call for current package rates."}], "quotationPdf": null, "categories": ["Bridal Service"], "districts": ["Colombo"]}', 4.6, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-49', 'Brides Mark', 'Bridal Service', 'Yakkala', 'Gampaha', '15000-147000', 'Bridal saree sale and rent plus frock hire at Kandy Road, Yakkala. Special bridal makeup packages with 30% offer: bride-only Rs. 98,000 and Silver party Rs. 147,000.', '{"images": [], "quotations": [{"id": "bm-saree-fit", "title": "Bridal saree 1st fit-on", "price": "60000", "details": "Was Rs. 80,000."}, {"id": "bm-saree-rent", "title": "Bridal saree rent", "price": "35000", "details": "Was Rs. 50,000. Other saree rents from Rs. 20,000."}, {"id": "bm-frock", "title": "Frock rent", "price": "15000", "details": "Was Rs. 25,000."}, {"id": "bm-bride", "title": "Only Bride Package (offer)", "price": "98000", "details": "Was 140,000. 4K/airbrush makeup, fresh bouquet, headdress, jewellery, free gold facial, threading, nails, mother''s dressing."}, {"id": "bm-sv", "title": "Silver Package (offer)", "price": "147000", "details": "Was 210,000. Bride package plus 2 bridesmaids (HD makeup, jewellery, bouquets, free Kandyan sarees) and 1 flower girl with free dress."}], "quotationPdf": null, "categories": ["Bridal Service"], "districts": ["Gampaha"]}', 4.6, 1, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-50', 'Salon Live Bridal', 'Bridal Service', 'Colombo', 'Colombo', '50000-200000', 'Bridal salon specialising in traditional Kandyan dressing and jewellery styling.', '{"images": [], "quotations": [{"id": "sl-bridal", "title": "Bridal dressing", "price": "", "details": "Kandyan bridal hair, makeup and dressing. Contact salon for 2026 rates."}], "quotationPdf": null, "categories": ["Bridal Service"], "districts": ["Colombo"]}', 4.5, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-51', 'Greens Flower Creations', 'Floral & Deco', 'Ja-Ela', 'Gampaha', '30000-500000', 'Premium hand-crafted flowers, 10+ years, 1000+ clients, hotel and banquet relationships. Church, poruwa, entrance, tables, oil lamp, settee, cards, bouquets, head decor, vehicles.', '{"images": [], "quotations": [{"id": "gf-wed", "title": "Wedding floral decoration", "price": "", "details": "Church, poruwa, entrance, pathway, head table, oil lamp, settee. Also engagements, homecomings, anniversaries. Call for a site quotation."}], "quotationPdf": null, "categories": ["Floral & Deco"], "districts": ["Gampaha"]}', 4.7, 1, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-52', 'Grooms Art', 'Groom service', 'Colombo', 'Colombo', '25000-150000', 'Men''s wear design studio. Promotional 50% discount on selected groom wear.', '{"images": [], "quotations": [{"id": "ga-wear", "title": "Groom wear (promo)", "price": "", "details": "Men''s wear design studio. 50% discount advertised on flyer. Call for fittings."}], "quotationPdf": null, "categories": ["Groom service"], "districts": ["Colombo"]}', 4.5, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-53', 'Grand Flora Weddings and Events', 'Floral & Deco', 'Pitakotte', 'Colombo', '50000-800000', 'Weddings and events florist with Pitakotte and Kiribathgoda branches. Beyond your expectations.', '{"images": [], "quotations": [{"id": "gfl-wed", "title": "Wedding floral & events", "price": "", "details": "Poruwa, stage, centrepieces and full event flowers. Branches in Pitakotte and Kiribathgoda."}], "quotationPdf": null, "categories": ["Floral & Deco"], "districts": ["Colombo"]}', 4.7, 1, 'info@grandfloralk.com');
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-54', 'Gayan Dissanayake Photography', 'Photography & Videography', 'Colombo', 'Colombo', '100000-500000', 'Weddings, fashion and lifestyle photography. Exclusive looks for 2025-2026.', '{"images": [], "quotations": [{"id": "gd-wed", "title": "Wedding / fashion / lifestyle", "price": "", "details": "Contact via social QR on the 2025 flyer for current wedding rates."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.6, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-55', 'Moonshadow Studio', 'Photography & Videography', 'Colombo', 'Colombo', '80000-400000', 'Est. 2015. Engagements, weddings, homecomings and casual sessions.', '{"images": [], "quotations": [{"id": "ms-wed", "title": "Wedding / engagement / homecoming", "price": "", "details": "Studio est. 2015. Contact for 2026 session rates."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.6, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-56', 'Creative Minds', 'Photography & Videography', 'Kiribathgoda', 'Gampaha', '80000-400000', 'Wedding photography, cinematography, portraits, commercial, events and wedding planning. Create your story with Creative Minds.', '{"images": [], "quotations": [{"id": "cm-wed", "title": "Wedding photography & cinematography", "price": "", "details": "Also portrait, commercial, event photography and wedding planning. Kiribathgoda."}], "quotationPdf": null, "categories": ["Photography & Videography", "Floral & Deco"], "districts": ["Gampaha"]}', 4.6, 0, 'creativemindswedding@gmail.com');
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-57', 'Amora Lagoon', 'Venue & Res. Halls', 'Katunayake', 'Gampaha', '200000-800000', 'Katunayake lagoon venue. Majestic Amora special wedding package with bites (limited offer) and Tide & Vows exclusive outdoor-wedding offer.', '{"images": [], "quotations": [{"id": "am-bites", "title": "Majestic Amora special wedding package with bites", "price": "", "details": "Limited offer. Call 076 443 2950 / 076 441 5109."}, {"id": "am-out", "title": "Tide & Vows outdoor wedding offer", "price": "", "details": "Exclusive outdoor wedding package. Same venue contacts."}], "quotationPdf": null, "categories": ["Venue & Res. Halls", "Caters"], "districts": ["Gampaha"]}', 4.6, 1, 'info@amora.lk');
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-58', 'Lanka Chandani Cake Creations', 'Cakes', 'Kadawatha', 'Gampaha', '15000-150000', 'Wedding cakes to your style and budget. Showroom Kiribathgoda / Mahara, Kadawatha.', '{"images": [], "quotations": [{"id": "lc-wed", "title": "Custom wedding cake", "price": "", "details": "Multi-tier floral wedding cakes. Express your wish - they create it. Showroom Kiribathgoda."}], "quotationPdf": null, "categories": ["Cakes"], "districts": ["Gampaha"]}', 4.7, 1, 'chandanicreations@gmail.com');
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-59', 'Swarnamahal', 'Jewellary', 'Colombo', 'Colombo', '50000-2000000', 'Bridal jewellery for all life''s golden moments. Free life insurance cover, free gold ring offer, installment facility, necklace and ring without labour charge on selected lines. SOUL bangle and ring collection.', '{"images": [], "quotations": [{"id": "sw-bridal", "title": "Bridal jewellery", "price": "", "details": "Necklace, earrings, bangles and rings. Installments and selected no-labour-charge pieces."}, {"id": "sw-soul", "title": "SOUL collection", "price": "", "details": "Gold bangle and ring line highlighted on the bridal flyer."}], "quotationPdf": null, "categories": ["Jewellary"], "districts": ["Colombo"]}', 4.7, 1, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-60', 'Dilanthi Cake', 'Cakes', 'Colombo', 'Colombo', '10000-80000', 'Professional cake designer: wedding cakes, cupcakes, jar cakes, structures, birthday and event cakes.', '{"images": [], "quotations": [{"id": "dc-wed", "title": "Wedding cake / structures", "price": "", "details": "Wedding, cup, jar, structure and event cakes. Contact designer for 2026 quotes."}], "quotationPdf": null, "categories": ["Cakes"], "districts": ["Colombo"]}', 4.5, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-61', 'TRI8SLK Weddings', 'Floral & Deco', 'Colombo', 'Colombo', '50000-400000', 'Trusted wedding planner. Stress-free planning, trusted vendor network, seamless day execution. Free wedding website for every couple.', '{"images": [], "quotations": [{"id": "tr-plan", "title": "Full wedding planning", "price": "", "details": "Planning, vendor network and day execution. Free wedding website included."}], "quotationPdf": null, "categories": ["Floral & Deco"], "districts": ["Colombo"]}', 4.6, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-62', 'Paradise Inn Bolgoda', 'Venue & Res. Halls', 'Bolgoda', 'Kalutara', '100000-1500000', 'Bolgoda Lake venue: Grand Ballroom 4000 sq ft / 300 pax, Crystal Ballroom 150-350 with lake and garden access, Rizta/Rista Banquet 100-150, garden weddings. In-house floral team with 50% discount offer on poruwa, settee, tables, entrance, oil lamps, garden lights and marquee letters.', '{"images": [], "quotations": [{"id": "pi-grand", "title": "Grand Ballroom", "price": "", "details": "4000 sq ft, 300 guests, open design."}, {"id": "pi-crystal", "title": "Crystal Ballroom", "price": "", "details": "150-350 guests, Bolgoda Lake and garden access."}, {"id": "pi-rizta", "title": "Rizta / Rista Banquet", "price": "", "details": "Intimate 100-150 guests."}, {"id": "pi-garden", "title": "Garden wedding", "price": "", "details": "Outdoor lake-view celebration."}, {"id": "pi-flora", "title": "Floral deco (50% offer)", "price": "", "details": "Fresh and artificial: poruwa, settee, tables, entrance, head table, oil lamp, garden lights, pool lanterns, couple/love marquee letters."}], "quotationPdf": null, "categories": ["Venue & Res. Halls", "Floral & Deco", "Caters"], "districts": ["Kalutara"]}', 4.6, 1, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-63', 'Isiwara Siritha', 'Floral & Deco', 'Colombo', 'Colombo', '40000-400000', 'One team, one vision, one perfect wedding. Decorations, dance group, poruwa ceremony, wedding planning and Nilame dress.', '{"images": [], "quotations": [{"id": "is-deco", "title": "Wedding decorations & poruwa", "price": "", "details": "Full traditional deco and poruwa ceremony."}, {"id": "is-dance", "title": "Dance group", "price": "", "details": "Traditional wedding dance team."}, {"id": "is-plan", "title": "Wedding planning", "price": "", "details": "End-to-end coordination."}, {"id": "is-nilame", "title": "Nilame dress", "price": "", "details": "Traditional groom attire hire/styling."}], "quotationPdf": null, "categories": ["Floral & Deco", "Groom service"], "districts": ["Colombo"]}', 4.5, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-64', 'Marji Flora', 'Floral & Deco', 'Ja-Ela', 'Gampaha', '25000-400000', 'The true beauty of flowers. Church, poruwa, settee, lamp, cake structures, tables, entrance, champagne and milk fountains, bridal bouquets and car decorations.', '{"images": [], "quotations": [{"id": "mf-full", "title": "Full floral decoration", "price": "", "details": "Church, poruwa, settee, lamps, cake structures, tables, head table, entrance, fountains, bouquets, cars."}], "quotationPdf": null, "categories": ["Floral & Deco"], "districts": ["Gampaha"]}', 4.6, 0, NULL);
INSERT IGNORE INTO vendor_listings (id, name, category, city, district, price_range, description, portfolio_json, rating, spotlight, owner_email) VALUES ('vw-65', 'Thambapanni Weddings', 'Photography & Videography', 'Colombo', 'Colombo', '80000-300000', 'One-day wedding packages. Traditional Kandyan and contemporary coverage.', '{"images": [], "quotations": [{"id": "th-1d", "title": "One day wedding package", "price": "", "details": "One-day wedding photography packages. See printed guide for album and enlargement options."}], "quotationPdf": null, "categories": ["Photography & Videography"], "districts": ["Colombo"]}', 4.5, 0, NULL);
